language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python tests.py
services:
- mongodb
notifications:
  slack:
    secure: pqnQMhYHOfJhYpf1tKnLXfvnvdyPv1l/wLGyzJHr8rQnFgRgu0OnDcc8XmEZOyRRuc8GJnfCde124+wxbmftRGSCZcdRuKdxKi9a+js9CHSHJ5ktnMEspZAEgejGeoMr7QFAY+hGZ/rShQoze4X2Zm67vdDyCodRVwWEth+vlLtQ6w+49vtVujf+Md1oBIhERu6Anokzx9fwgI9bJFseO0P7kbvah7RzrOSw18PSevOVTx1X0+nK1Nbaxch+McJ0iFgdUzPny+8jwuot8mMS7e84Cp5B6/g2reSHXMZdHFClEFK6FJxNnZnKiWzrmFLVhlamepIv9ZppzqDFZdrjy4td62ChqzCtnewrmUNVSvVaoIwGQ3vnDO9by8NBtSsi9DTNeUFECZhLair3MXHuA/m1pb3bJmT0UCoegRWfc0PXHL8jCfCRf9lWnK0yr5dmKR0Cdvrjni1P60kSM/Gu8hPripSm/tlYedjbYlXMiy6Zzxz2UMKNavkDRDcwPqJQdHomyRy+R2qByUMgExNxiNjQ+ybIqI/TYB7iTMFlBk96rRStFWdHbiFD4OH19VcmuJde9BhzCUZOXqSpBf1UNVpT/82egEY/LWSTRYol1zs6nMkB9d9mXDPKLvqK4fn0k/wmb+bvRRBg/Sv31rU1umpYX0pvN+5RFcx4i7e3rWE=
deploy:
  provider: heroku
  api_key:
    secure: LJDHKaPl/vGm++ihSP58/M/Vi9+Rnahv/Uwss0meEYEcojWJhQDDkTBe3gjQf8ak2oo4uuXA8V1DqIXPQGF4F2MQm6J9zZ8l2nBeZPdLLd344PA7XZkriSW6Lb2suzsgmcSIH1FaTi0lGJkLvvS3gap58cm51So8Ho7X0EsFIHMX0MYnHFUNINcsp4cuEbhC8zGu/xtcOCEfFQDdWKzYFNPRFgX1njf/Kv84TOZMatS08XN++MAKfglFwd0hNF8KUNEhqLhCy3QFCO4DWSw+0Yd3i7oD9yOHZiSJupp8qFjaATgNKJse3JAdfs62C8zEd4Hupd0bY2DH7oP4/YODo9IZLMOKgS1TfiywXNs8Xhyv5if6QcUSTq8896SNSfzaUxSKbrBef9kzo0acjm2Na2DRLIbCboFfLlFKaxgw9Tyb5G81AiMPO7sz4tSqcDrt9Gw22Sl7kaNasnw+ygSoPt1Bz2JSeDQCJLU/V9tVUtoyW+H/N6uy4k5mBrCrzgFix5gHOaRh6CpkvLRssIGt9fYCz0bGnNbFmdn/kyvZ7J3EhZuok/XAqr+w/vSDUXn6rV54IHU6eXJBJs6bwI8ZnNW8YYzz+fnnWrm9jaNTvLZwdtN8habmqpXbflIpcccvJWlXb7yiXBFTAXNPqOc3AZx23AAU9/pDaOdMAed8oyk=
  app: legislation-tagger
  on:
    repo: Doteveryone/LegislationTagger
